@startuml 
:User: --> (Use)
"Monitor" as Admin
"Cadastrar" as (Use)
Admin --> (Relatórios)
@enduml

@startuml 
:U: --> (Use)
"Monitor" as Admin
"Cadastrar" as (Use)
Admin --> (Relatórios)
@enduml

@startuml
class Car
Driver - Car : drives >
Car *- Wheel : have 4 >
Car -- Person : < owns
@enduml

